# Default configuration is required and will be loaded first. Model-specific configurations will override default settings when provided.

default:
  validation:
    num_samples: 1000
    step_num: best # "best", "latest" or step_number:integer are available
  test:
    num_samples: 753
    step_num: best # "best", "latest" or step_number:integer are available

qwen-25-3b:
  validation:
    num_samples: 1000
    step_num: 106000
  test:
    num_samples: 218
    step_num: 106000
qwen-25-7b:
  validation:
    num_samples: 1000
    step_num: 57000
  test:
    num_samples: 218
    step_num: 57000
llama-32-11b:
  validation:
    num_samples: 1
    step_num: 21000
  test:
    num_samples: 753
    step_num: 21000
# CRNN model configuration
crnn-base-3m:
  validation:
    num_samples: 1000
    step_num: latest
  test:
    num_samples: 218
    step_num: latest
